config/routes.rb
Hive::Scheduler::Application.routes.draw do
  get 'artifacts/create'

  root 'batches#index'

  resources :batches, only: %w[index show new create] do
    get :chart_data
    get 'filter/:state', on: :collection, action: :filter, as: :filter
    get ':state', action: :filter_jobs, as: :filter
  end

  resources :jobs, only: %w[show] do
    put :retry
    put :cancel
  end

  resources :projects

  namespace :api, defaults: { format: :json } do
    patch '/queues/:queue_names/jobs/reserve' => 'jobs#reserve', defaults: { format: :json }, constraints: { queue_names: /[^\/]*/ }
    post '/jobs/:job_id/artifacts' => 'artifacts#create', defaults: { format: :json }

    resources :batches, only: %w[create show index] do
      get :download_build
      get '/download_build/:file_name', action: :download_build
    end
    resources :jobs do
      patch :prepare
      patch :start
      patch :end
      patch :update_results
      patch :complete
      patch :error
      put :report_artifacts
    end
    resources :projects do
      get :show
    end
  end

  namespace :admin do
    resources :scripts, except: %w[destroy]
  end

  get '/queues' => 'monitoring#dashboard'
  post '/queues/:hive_queue_id/cancel' => 'monitoring#cancel_jobs'
  get '/workers' => 'monitoring#workers'
  get '/usage' => 'monitoring#usage'
  get '/job_status' => 'monitoring#job_status'
  get '/job_status/project/:project_id' => 'monitoring#job_status_project_graph', as: 'job_status_project'

  # Usage stats as json
  get '/usage/batch_counts' => 'monitoring#batch_counts'
  get '/usage/project_counts' => 'monitoring#project_counts'
  get '/usage/device_hours' => 'monitoring#device_hours'

  post '/batches/:id/cancel' => 'batches#cancel_jobs'

  get '/status' => 'api/status#show'

  # Omniauth callbacks
  post '/auth/:provider/callback' => 'application#auth_callback'
  get '/auth/:provider/callback' => 'application#auth_callback'
end

app/controllers/monitoring_controller.rb
class MonitoringController < ApplicationController
  def dashboard
    # This callback is very expensive, turn it off when execution_variables aren't important
    Project.skip_callback(:initialize, :after, :set_default_execution_variables)

    @queues = HiveQueue.joins(:workers).where('workers.updated_at > ?', 5.minutes.ago).uniq

    @queued_jobs = Job.includes(job_group: [:hive_queue], script: [:target]).where(state: %i[queued reserved running]).order(created_at: :asc).group_by { |j| j.job_group.hive_queue }

    @queues = @queues.sort { |a, b| (@queued_jobs[b] ? @queued_jobs[b].count : 0) <=> (@queued_jobs[a] ? @queued_jobs[a].count : 0) }

    @queues_with_no_workers = @queued_jobs.reject { |q, _j| @queues.include? q }.keys
  end

  def workers
    Project.skip_callback(:initialize, :after, :set_default_execution_variables)
    @workers = Worker.where('updated_at > ?', 5.minutes.ago)
  end

  def cancel_jobs
    hive_queue_id = params[:hive_queue_id]

    jobs = Job.joins(:job_group).where('job_groups.hive_queue_id = ? ', hive_queue_id).where(state: %i[queued reserved running])

    jobs.each(&:cancel)

    redirect_to '/queues'
  end

  def usage
    @batch_count_url = usage_batch_counts_path
  end

  def batch_counts
    months = params[:months].to_i == 0 ? 24 : params[:months].to_i
    @monthly_counts = Hive::UsageCounts.batch_counts(months: months)
  end

  def project_counts
    months = params[:months].to_i == 0 ? 18 : params[:months].to_i
    @project_counts = Hive::UsageCounts.project_counts(months: months)
  end

  def device_hours
    days = params[:days].to_i == 0 ? 6 : params[:days].to_i
    @device_hours = Hive::UsageCounts.device_hours(days: days)
  end

  def job_status
    jbs = Job.slo_core_hours.joins(job_group: :hive_queue)

    @description = "Breakdown of job status between 9:00 and 17:00 on #{1.day.ago.strftime('%A %d %B %Y')}"
    if jbs.count > 0

      @job_queue_data = [parse_job_status('All queues', jbs)]
      @job_project_data = [parse_job_projects_status('All projects', -1, jbs)]

      by_group = jbs.group_by { |j| j.job_group.hive_queue }
      by_project = jbs.group_by(&:project)

      @tmp_data = []
      by_group.each_pair do |q, data|
        @tmp_data << parse_job_status(q.name, data)
      end

      @job_queue_data += @tmp_data.sort_by { |a| a[:queue] }

      @tmp_data = []
      by_project.each_pair do |p, data|
        @tmp_data << parse_job_projects_status(p.name, p.id, data)
      end

      @job_project_data += @tmp_data.sort_by { |a| a[:project] }
    else
      @job_queue_data = []
      @job_project_data = []
    end
  end

  def job_status_project_graph
    respond_to do |format|
      format.html do
      end
      format.json do
        where = 'jobs.created_at > ? AND state = ?'
        where_opts = [31.days.ago, 'complete']
        if params[:project_id].to_i > 0
          where += ' AND project_id = ?'
          where_opts << params[:project_id]
        end

        data = {}
        Job.joins(:batch)
           .where([where, where_opts].flatten)
           .group('date(jobs.created_at)')
           .group(:result)
           .count.each_pair do |keys, count|
          unless data.key? keys[0]
            data[keys[0]] = {
              date: keys[0].strftime('%F'),
              total: 0
            }
          end
          data[keys[0]][keys[1].to_sym] = count
          data[keys[0]][:total] += count
        end

        render json: data.values.map { |row|
          {
            date: row[:date],
            passed: 100.0 * row[:passed].to_f / row[:total],
            failed: 100.0 * row[:failed].to_f / row[:total],
            errored: 100.0 * row[:errored].to_f / row[:total]
          }
        }
      end
    end
  end

  private

  def parse_job_status(queue, data)
    not_cancelled = data.reject { |d| d.status == 'cancelled' }
    qd = not_cancelled.select { |d| d.start_time.nil? }
    one_min = not_cancelled.select { |d| d.start_time && d.start_time - d.created_at < 1.minute }
    two_min = not_cancelled.select { |d| d.start_time && d.start_time - d.created_at < 2.minute }
    twenty_mins = not_cancelled.select { |d| d.start_time && d.start_time - d.created_at < 20.minutes }
    results = {}
    %w[passed failed errored].each do |r|
      results[r] = not_cancelled.select { |d| d.status == r }
    end
    {
      queue: queue,
      count: data.count,
      cancelled: data.count - not_cancelled.count,
      pc_queued: 100.0 * qd.count / not_cancelled.count,
      pc_1_min: 100.0 * one_min.count / not_cancelled.count,
      pc_2_min: 100.0 * two_min.count / not_cancelled.count,
      pc_20_min: 100.0 * twenty_mins.count / not_cancelled.count
    }
  end

  def parse_job_projects_status(project, project_id, data)
    not_cancelled = data.reject { |d| d.status == 'cancelled' }
    qd = not_cancelled.select { |d| d.start_time.nil? }
    results = {}
    %w[passed failed errored].each do |r|
      results[r] = not_cancelled.select { |d| d.status == r }
    end
    {
      project: project,
      project_id: project_id,
      count: data.count,
      cancelled: data.count - not_cancelled.count,
      pc_queued: 100.0 * qd.count / not_cancelled.count,
      passed: results['passed'].count,
      passed_pc: 100.0 * results['passed'].count / data.count,
      failed: results['failed'].count,
      failed_pc: 100.0 * results['failed'].count / data.count,
      errored: results['errored'].count,
      errored_pc: 100.0 * results['errored'].count / data.count
    }
  end
end

app/views/monitoring/dashboard.html.erb
<head>
  <% provide(:title, "Queues") %>
</head>
<h2>Queues</h2>
<br/>

<table class="queue-table">
  <% @queues_with_no_workers.each do |queue| %>
      <tbody>
      <tr>
        <td>
          <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                      "/queues/#{queue.id}/cancel",
                      :method => :cancel,
                      :data => {:confirm => "This will cancel all jobs on this queue, are you sure?"} %>
        <td><span class="label label-info"><%= queue.name -%></span></td>
        <td>
          <span class="glyphicon glyphicon-exclamation-sign warning-color" data-toggle="tooltip" data-placement="top" title="No workers available for queue"></span>
        </td>
        <td>
          <% if jobs = @queued_jobs[queue] %>
              <% jobs.each do |j| %>
                  <%= job_span(j) -%>
              <% end %>
          <% end %>
        </td>
      </tr>
      </tbody>
  <% end %>

  <% @queues.each do |queue| %>
      <tbody>
      <tr>
        <td>
          <% if @queued_jobs[queue] %>
              <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                          "/queues/#{queue.id}/cancel",
                          :method => :cancel,
                          :data => {:confirm => "This will cancel all jobs on this queue, are you sure?"} %>
          <% end %>
        </td>
        <td><span class="label label-info"><%= queue.name -%></span></td>
        <td>
          <% worker_count = queue.workers.active.count %>
          <span class="glyphicon glyphicon-cog ok-color" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="<%= worker_count -%> workers waiting for jobs"> <strong><%= worker_count -%></strong></span>
        </td>
        <td>
          <% if jobs = @queued_jobs[queue] %>
              <% jobs.each do |j| %>
                  <%= job_span(j) -%>
              <% end %>
          <% end %>
        </td>
      </tr>
      </tbody>
  <% end %>
</table>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

app/views/monitoring/job_status.html.erb
<head>
  <% provide(:title, "Job Status") %>
</head>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3>Job status</h3>

    <p><%= @description %></p>
  </div>
  <div class="panel-body">
    <ul class='nav nav-tabs'>
      <li class='active'><a data-toggle='tab' href='#starts'>Starting</a></li>
      <li><a data-toggle='tab' href='#states-table'>States (table)</a></li>
      <li><a data-toggle='tab' href='#states-graph'>States (graph)</a></li>
      <li><a data-toggle='tab' href='#file-list'>Stats files</a></li>
    </ul>
    <div class='tab-content'>
      <div id='starts' class='tab-pane fade in active'>
        <p>Percentages exclude cancelled jobs</p>
        <table class='table table-striped'>
          <thead>
            <tr>
              <th>Queue</th>
              <th>Jobs</th>
              <th>Cancelled</th>
              <th>% queued</th>
              <th>% start within 1 minute</th>
              <th>% start within 2 minute</th>
              <th>% start within 20 minutes</th>
            </tr>
          </thead>
          <tbody>
            <% @job_queue_data.each do |jsd| %>
            <tr>
              <td><%= jsd[:queue] %></td>
              <td><%= jsd[:count] %></td>
              <td><%= jsd[:cancelled] %></td>
              <td><%= jsd[:pc_queued].round(2) %></td>
              <td><%= jsd[:pc_1_min].round(2) %></td>
              <td><%= jsd[:pc_2_min].round(2) %></td>
              <td><%= jsd[:pc_20_min].round(2) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id='states-table' class='tab-pane fade'>
        <p>Percentages include cancelled jobs</p>
        <table class='table table-striped'>
          <thead>
            <tr>
              <th>Project</th>
              <th>Jobs</th>
              <th>Cancelled</th>
              <th>Passed</th>
              <th>Failed</th>
              <th>Errored</th>
            </tr>
          </thead>
          <tbody>
            <% @job_project_data.each do |jsd| %>
            <tr>
              <td><%= link_to jsd[:project], job_status_project_path(jsd[:project_id]) %></td>
              <td><%= jsd[:count] %></td>
              <td><%= jsd[:cancelled] %></td>
              <td><%= jsd[:passed] %> (<%= jsd[:passed_pc].round(2)%>%)</td>
              <td><%= jsd[:failed] %> (<%= jsd[:failed_pc].round(2)%>%)</td>
              <td><%= jsd[:errored] %> (<%= jsd[:errored_pc].round(2)%>%)</td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id='states-graph' class='tab-pane fade'>
        <p>Percentages include cancelled jobs</p>
        <table class='table table-striped'>
          <thead>
            <tr>
              <th class='col-md-2'>Project</th>
              <th class='col-md-10'></th>
            </tr>
          </thead>
          <tbody>
            <% @job_project_data.each do |jsd| %>
            <tr>
              <td><%= jsd[:project] %></td>
              <td>
                <div class='progress'>
    <% puts jsd.inspect %>
                  <div class='progress-bar progress-bar-success' role='progressbar' style='width:<%= jsd[:passed_pc] %>%'><%= jsd[:passed_pc].round(0) %></div>
                  <div class='progress-bar progress-bar-danger' role='progressbar' style='width:<%= jsd[:failed_pc] %>%'><%= jsd[:failed_pc].round(0) %></div>
                  <div class='progress-bar progress-bar-info' role='progressbar' style='width:<%= jsd[:errored_pc] %>%'><%= jsd[:errored_pc].round(0) %></div>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id='file-list' class='tab-pane fade'>
        <ul>
        <% Dir.glob("#{Rails.public_path}/stats/*").map{ |f| f.remove(Rails.public_path.to_s + '/') }.sort{|a, b| b<=>a}.each do |f| %>
          <li><%= link_to f, root_path << f %> </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/monitoring/job_status_project_graph.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3>Pass/Fail/Error for project</h3>
  </div>

  <div class="panel-body">
    <svg class="project-state-chart" width="100%" height="400"></svg>
  </div>
</div>

<script>
  d3.json("<%= job_status_project_path(params[:project_id]) %>.json", function(error, json) {
    if (error) return console.warn(error);
    renderD3LineChart('.project-state-chart', json);
  });
</script>

app/views/monitoring/usage.html.erb
<head>
  <% provide(:title, "Usage") %>
</head>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3>Batch counts</h3>

    <p>Batches triggered per calendar month</p>
  </div>
  <div class="panel-body">
    <svg class="usage-charts monthly-batch-counts" width="100%" height="400"></svg>

  </div>
</div>


<script>
    d3.json("<%= usage_batch_counts_path -%>.json", function (error, json) {
        if (error) return console.warn(error);
        renderD3BarChart('.monthly-batch-counts', json, '#428bca', 'lightsteelblue');
    });
</script>


<div class="row">

  <div class="col-md-6">

    <div class="panel panel-info">
      <div class="panel-heading">
        <h3>Projects counts</h3>

        <p>Active projects each calendar month</p>
      </div>
      <div class="panel-body">
        <svg class="usage-charts monthly-project-counts" width="100%" height="300"></svg>
      </div>
    </div>
  </div>

  <div class="col-md-6">

    <div class="panel panel-success">
      <div class="panel-heading">
        <h3>Device hours</h3>

        <p>Hours spent testing this week</p>
      </div>
      <div class="panel-body">
        <svg class="usage-charts daily-device-hours" width="100%" height="300"></svg>
      </div>
    </div>
  </div>

</div>


<script>
    d3.json("<%= usage_project_counts_path -%>.json", function (error, json) {
        if (error) return console.warn(error);
        renderD3BarChart('.monthly-project-counts', json, 'lightsteelblue', 'steelblue');
    });

    d3.json("<%= usage_device_hours_path -%>.json", function (error, json) {
        if (error) return console.warn(error);
        renderD3BarChart('.daily-device-hours', json, 'mediumseagreen', 'lightseagreen');
    });
</script>

app/views/monitoring/workers.html.erb
<head>
  <% provide(:title, "Hive Workers") %>
</head>
<h2>Hive Workers</h2>
<br/>

<% if @workers.count == 0 %>

    <p class="lead">No workers currently polling the hive</p>

    <p>You might want to start some up!</p>

<% else %>

    <p class="lead">Workers currently polling for jobs</p>

    <table class="table table-condensed">
      <thead>
      <tr>
        <th>Hive</th>
        <th>Pid</th>
        <th>Status</th>
        <th>Device</th>
        <th>Queues</th>
      </tr>
      </thead>
      <% @workers.each do |worker| %>
          <tr>
            <td><%= worker.hive_id.to_i > 0 ? worker.hive_id : '?' -%></td>
            <td><%= worker.pid -%></td>
            <% if worker.status == :active %>
                <td><span class="label label-success">Active</span></td>
            <% else %>
                <td><span class="label label-failure">Inactive</span></td>
            <% end %>
            <% if worker.device_id %>
                <td><%= worker.device_id %></td>
            <% else %>
                <td><span class="glyphicon glyphicon-question-sign"></span></td>
            <% end %>
            <td>
              <% worker.hive_queues.each do |queue| %>
                  <span class="label label-info"><%= queue.name -%></span>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>

<% end %>