config/routes.rb
Hive::Scheduler::Application.routes.draw do
  get 'artifacts/create'

  root 'batches#index'

  resources :batches, only: %w[index show new create] do
    get :chart_data
    get 'filter/:state', on: :collection, action: :filter, as: :filter
    get ':state', action: :filter_jobs, as: :filter
  end

  resources :jobs, only: %w[show] do
    put :retry
    put :cancel
  end

  resources :projects

  namespace :api, defaults: { format: :json } do
    patch '/queues/:queue_names/jobs/reserve' => 'jobs#reserve', defaults: { format: :json }, constraints: { queue_names: /[^\/]*/ }
    post '/jobs/:job_id/artifacts' => 'artifacts#create', defaults: { format: :json }

    resources :batches, only: %w[create show index] do
      get :download_build
      get '/download_build/:file_name', action: :download_build
    end
    resources :jobs do
      patch :prepare
      patch :start
      patch :end
      patch :update_results
      patch :complete
      patch :error
      put :report_artifacts
    end
    resources :projects do
      get :show
    end
  end

  namespace :admin do
    resources :scripts, except: %w[destroy]
  end

  get '/queues' => 'monitoring#dashboard'
  post '/queues/:hive_queue_id/cancel' => 'monitoring#cancel_jobs'
  get '/workers' => 'monitoring#workers'
  get '/usage' => 'monitoring#usage'
  get '/job_status' => 'monitoring#job_status'
  get '/job_status/project/:project_id' => 'monitoring#job_status_project_graph', as: 'job_status_project'

  # Usage stats as json
  get '/usage/batch_counts' => 'monitoring#batch_counts'
  get '/usage/project_counts' => 'monitoring#project_counts'
  get '/usage/device_hours' => 'monitoring#device_hours'

  post '/batches/:id/cancel' => 'batches#cancel_jobs'

  get '/status' => 'api/status#show'

  # Omniauth callbacks
  post '/auth/:provider/callback' => 'application#auth_callback'
  get '/auth/:provider/callback' => 'application#auth_callback'
end

app/models/concerns/project/project_associations.rb
class Project < ActiveRecord::Base
  module ProjectAssociations
    extend ActiveSupport::Concern

    included do
      belongs_to :script
      has_many   :batches
      has_many   :assets
      has_many   :test_cases

      has_one    :latest_batch, -> { order id: :desc }, class_name: 'Batch'
    end
  end
end

app/models/concerns/project/project_callbacks.rb
class Project < ActiveRecord::Base
  module ProjectCallbacks
    extend ActiveSupport::Concern

    included do
      after_initialize do |project|
        project.builder_options = {} unless project.builder_options.present?
      end
    end
  end
end

app/models/concerns/project/project_validations.rb
class Project < ActiveRecord::Base
  module ProjectValidations
    extend ActiveSupport::Concern

    included do
      validates :name, :script, :execution_directory, presence: true
      validates :name, uniqueness: true
      validates :builder_name, presence: true, 'builders/validators/builder_name' => true
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ProjectValidations
  include ProjectAssociations
  include ProjectCallbacks
  acts_as_paranoid

  serialize :builder_options, JSON
  serialize :execution_variables, JSON

  delegate :requires_build?, :target, to: :script, allow_nil: true

  after_initialize :set_default_execution_variables

  def set_default_execution_variables
    self.execution_variables = HashWithIndifferentAccess.new unless execution_variables.present?
    execution_variables_required.each do |required_execution_variable|
      execution_variables[required_execution_variable.name.to_s] = required_execution_variable.default_value unless execution_variables[required_execution_variable.name.to_s].present?
    end
  end

  def execution_variables_required
    if @execution_variables_required.nil?
      @execution_variables_required = []
      @execution_variables_required |= script.execution_variables if script.present?
      @execution_variables_required |= builder.execution_variables_required if builder.present?
    end
    @execution_variables_required
  end

  def builder
    @builder ||= Builders::Registry.find_by_builder_name(builder_name)
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::ApiController
  include Roar::Rails::ControllerAdditions
  respond_to :json

  def show
    @project = Project.find_by_id(params[:id])
    if @project.present?
      respond_with @project, represent_with: ProjectRepresenter
    else
      render status: :not_found, json: { errors: [t('.not_found')] }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]
  before_action :set_builders, only: [:edit]

  # GET /projects
  def index
    @projects = Project.all.reverse
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id])
    @related_projects = @project.script.projects.where('id != ?', @project.id)
  end

  # GET /projects/new
  def new
    @project = Project.new(params[:project].blank? ? {} : project_params)
    set_builders

    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      set_builders
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by_id(params[:id])
  end

  def set_builders
    @selected_builder = Builders::Registry.find_by_builder_name(@project.builder_name)
    @builders         = Builders::Registry.registered_builders
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    if @project_params.nil?
      @project_params = params.require(:project).permit(:name, :platform, :plan_id, :script_id, :builder_name, :repository, :branch, :execution_directory, :retries)
      @project_params[:builder_options] = params[:project][:builder_options]
      @project_params[:execution_variables] = params[:project][:execution_variables]
    end
    @project_params
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :repository %>
  <%= f.input :branch %>
  <%= f.input :execution_directory %>
  <%= f.association :script %>

  <% if @builders.present? %>
    <%= field_set_tag "Population Mechanism" do %>
      <%= f.input :builder_name, collection: @builders, value_method: :builder_name, label_method: :friendly_name, label: "Population Mechanism" %>

      <% if @selected_builder.present? %>
        <%= f.fields_for :builder_options, OpenStruct.new(@project.builder_options) do |builder_options_builder| %>

          <% @selected_builder.dependencies.each do |dependency| %>

            <%= render "fields/#{dependency.field_type}", field_name: dependency.name, f: builder_options_builder %>
          <% end unless @selected_builder.dependencies.blank? %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= render "shared/execution_variables", f: f, model: @project %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn' %>
  </div>

<% end %>

<% if @project.script.present? %>
  <script type="text/javascript">
    $('#template_preview').removeClass('hidden');
  </script>
  <pre id="template_preview" class="hidden"><%= @project.script.template.html_safe %></pre>
<% end %>

app/views/projects/edit.html.erb
<head>
  <% provide(:title, "Edit Project: #{@project.name}") %>
</head>
<%- model_class = Project -%>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<head>
  <% provide(:title, "Projects") %>
</head>
<%- model_class = Project -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th>Name</th>
    <th><%= model_class.human_attribute_name(:script) %></th>
    <th>Modified</th>
    <th>Last Run</th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><span class="label label-project"><%= project.id %></span></td>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= link_to project.script.name, edit_admin_script_path(project.script) %></td>
        <td><%= time_ago_in_words(project.updated_at) %></td>
        <% if project.batches.last %>
            <td><%= time_ago_in_words(project.batches.last.created_at) %></td>
        <% else %>
            <td>Not run</td>
        <% end %>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_project_path(project), :class => 'btn btn-default' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        project_path(project),
                        :method => :delete,
                        :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                        :class => 'btn btn-danger' %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<head>
  <% provide(:title, "Create A New Project") %>
</head>
<%- model_class = Project -%>
<div class="page-header">
  <h1>Create a new project</h1>

  <p>
    Projects describe how your tests should be run and provide the relevant information required for queuing up
    batches of test jobs.
    <br/>
    A project contains information such as the repository where your tests exist and how your batches of test jobs
    should be executed.
    <br/>
    A project is associated with a particular script and population mechanism, this combination enables the
    hive to batch your tests into jobs and execute your tests on the required devices.
  </p>
</div>

<%= render :partial => 'form' %>

app/views/projects/new.js.erb
$("#new_project").html("<%= escape_javascript(render partial: "projects/form") %>");
project_create();
array_field();

app/views/projects/show.html.erb
<head>
  <% provide(:title, "Project Details: #{@project.name}") %>
</head>
<div>
  <div>
    <span class="large-icon pull-right"><%= icon(@project.target.icon) %></span>

    <h1><%= @project.name -%></h1>
  </div>

  <div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#details" aria-controls="details" role="tab" data-toggle="tab">Details</a></li>
      <li role="presentation"><a href="#script" aria-controls="script" role="tab" data-toggle="tab">Script</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">

      <!-- Details Tab -->
      <div role="tabpanel" class="tab-pane active" id="details">

        <h3>Project Details</h3>

        <dl class="dl-horizontal">
          <dt><strong><%= Project.human_attribute_name(:script) %>:</strong></dt>
          <dd><%= @project.script.name %></dd>

          <dt><strong>Test Code repository:</strong></dt>
          <dd><%= @project.repository %></dd>
          <dt><strong>Branch:</strong></dt>
          <dd><%= @project.branch %></dd>
          <dt><strong>Execution directory:</strong></dt>
          <dd><%= @project.execution_directory %></dd>

          <% if @project.builder %>

              <dt><strong>Population Mechanism:</strong></dt>
              <dd><%= @project.builder.friendly_name %></dd>

              <% @project.builder_options.each_pair do |name, value| %>
                  <dt><strong><%= name.humanize %>:</strong></dt>
                  <dd><%= value %></dd>
              <% end %>

          <% else %>

              <dt><strong>Warning:</strong></dt>
              <dd>No builder associated with this project. Get help!</dd>

          <% end %>

          <% (@project.execution_variables || {}).each_pair do |name, value| %>
              <dt><strong><%= name.humanize %>:</strong></dt>
              <dd><%= value %></dd>
          <% end %>

          <dt><strong>Created:</strong></dt>
          <dd><%= @project.created_at.to_s(:long) %></dd>
          <dt><strong>Last modified:</strong></dt>
          <dd><%= @project.updated_at.to_s(:long) %></dd>
        </dl>

        <div class="form-actions">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(@project), :class => 'btn btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(@project),
                      :method => 'delete',
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-danger' %>
        </div>


      </div>
      <div role="tabpanel" class="tab-pane" id="script">

        <h3>Script: <%= @project.script.name -%></h3>

        <% if !@related_projects.empty? %>

            <p>This script is also in use by the following projects:</p>
            <table class="table">
              <% @related_projects.each do |p| %>
                  <tr>
                    <td>
                      <span class="label label-project"><%= link_to p.id, project_url(p) -%></span>
                    </td>
                    <td>
                      <%= link_to p.name, project_url(p) -%>
                    </td>
                    <% if p.batches.last %>
                        <td><%= time_ago_in_words(p.batches.last.created_at) %></td>
                    <% else %>
                        <td>Not run</td>
                    <% end %>
                    </td>
                  </tr>
              <% end %>

            </table>
        <% end %>


        <pre><%= @project.script.template -%></pre>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_script_path(@project.script), :class => 'btn btn-default btn-sm' %>
        </td>
        </pre>

      </div>
    </div>

  </div>
</div>