config/routes.rb
Hive::Scheduler::Application.routes.draw do
  get 'artifacts/create'

  root 'batches#index'

  resources :batches, only: %w[index show new create] do
    get :chart_data
    get 'filter/:state', on: :collection, action: :filter, as: :filter
    get ':state', action: :filter_jobs, as: :filter
  end

  resources :jobs, only: %w[show] do
    put :retry
    put :cancel
  end

  resources :projects

  namespace :api, defaults: { format: :json } do
    patch '/queues/:queue_names/jobs/reserve' => 'jobs#reserve', defaults: { format: :json }, constraints: { queue_names: /[^\/]*/ }
    post '/jobs/:job_id/artifacts' => 'artifacts#create', defaults: { format: :json }

    resources :batches, only: %w[create show index] do
      get :download_build
      get '/download_build/:file_name', action: :download_build
    end
    resources :jobs do
      patch :prepare
      patch :start
      patch :end
      patch :update_results
      patch :complete
      patch :error
      put :report_artifacts
    end
    resources :projects do
      get :show
    end
  end

  namespace :admin do
    resources :scripts, except: %w[destroy]
  end

  get '/queues' => 'monitoring#dashboard'
  post '/queues/:hive_queue_id/cancel' => 'monitoring#cancel_jobs'
  get '/workers' => 'monitoring#workers'
  get '/usage' => 'monitoring#usage'
  get '/job_status' => 'monitoring#job_status'
  get '/job_status/project/:project_id' => 'monitoring#job_status_project_graph', as: 'job_status_project'

  # Usage stats as json
  get '/usage/batch_counts' => 'monitoring#batch_counts'
  get '/usage/project_counts' => 'monitoring#project_counts'
  get '/usage/device_hours' => 'monitoring#device_hours'

  post '/batches/:id/cancel' => 'batches#cancel_jobs'

  get '/status' => 'api/status#show'

  # Omniauth callbacks
  post '/auth/:provider/callback' => 'application#auth_callback'
  get '/auth/:provider/callback' => 'application#auth_callback'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  include BatchValidations
  include BatchChart
  include BatchAssociations
  include BatchScopes

  serialize :target_information, JSON
  serialize :execution_variables, JSON

  delegate :requires_build?, to: :project, allow_nil: true
  delegate :execution_variables_required, to: :project, allow_nil: true

  self.per_page = 20

  default_value_for :number_of_automatic_retries, 1

  after_initialize :copy_execution_variables

  def copy_execution_variables
    if new_record? && project.present?
      execution_variables = (self.execution_variables || {}).delete_if { |_, value| value.blank? }
      self.execution_variables = (project.execution_variables || {}).merge(execution_variables)
    end
  end

  def tests_per_job
    execution_variables.with_indifferent_access[:tests_per_job].to_i
  end

  def jobs_per_queue
    execution_variables.with_indifferent_access[:jobs_per_queue]
  end

  def state
    unless @state_cache
      ordered_job_states = %i[errored failed queued reserved retried preparing running analyzing passed complete cancelled]
      job_states         = latest_jobs.collect { |job| job.status.to_sym }.uniq
      job_states = job_states.sort_by { |state| ordered_job_states.index(state) }
      @state_cache = job_states.find do |state|
        ordered_job_states.include?(state)
      end || :invalid
    end
    @state_cache
  end

  def test_result_count_hash
    unless @hash
      @hash = job_groups.collect { |g| g.test_results.group_by(&:test_case_id).collect { |_k, v| v.last } }.flatten.group_by(&:status)
      @hash['queued'] = @hash['notrun']
    end
    @hash
  end

  def active_job_states(state, result)
    unless @active_job_states
      @active_job_states = jobs.active.group('jobs.state').group('jobs.result').count
    end
    @active_job_states[[state, result]] || 0
  end

  #
  # These methods provide a summary of the job statuses
  #
  def jobs_queued
    active_job_states('queued', nil) + active_job_states('pending', nil)
  end

  def jobs_running
    active_job_states('preparing', nil) + active_job_states('running', nil) + active_job_states('analyzing', nil)
  end

  def jobs_passed
    active_job_states('complete', 'passed')
  end

  def jobs_failed
    active_job_states('complete', 'failed')
  end

  def jobs_errored
    jobs.active.where("jobs.state='errored' or jobs.state='cancelled' or ( jobs.state='complete' and jobs.result='errored')").count
  end

  def assets
    batch_assets.map(&:asset)
  end

  #
  # These methods give a total count of all tests in the batch
  #
  %i[queued running passed failed errored].each do |m|
    define_method("tests_#{m}") do
      if !test_cases.empty?
        (test_result_count_hash[m.to_s] || []).count
      else
        jobs.active.sum("#{m}_count")
      end
    end
  end
end

app/models/concerns/batch/batch_associations.rb
class Batch < ActiveRecord::Base
  module BatchAssociations
    extend ActiveSupport::Concern

    included do
      belongs_to :project, with_deleted: true
      has_one    :script, through: :project
      has_many   :job_groups, dependent: :destroy
      has_many   :jobs, through: :job_groups
      has_many   :project_assets, through: :project, foreign_key: 'version', source: :assets

      has_many   :test_cases, through: :project
      has_many   :batch_assets
    end
  end
end

app/models/concerns/batch/batch_chart.rb
class Batch < ActiveRecord::Base
  module BatchChart
    extend ActiveSupport::Concern

    def chart_data
      data = {
        queued: jobs_queued,
        running: jobs_running,
        passed: jobs_passed,
        failed: jobs_failed,
        errored: jobs_errored
      }
      Hive::ChartDataMangler.pie_result_data(data)
    end
  end
end

app/models/concerns/batch/batch_scopes.rb
class Batch < ActiveRecord::Base
  module BatchScopes
    extend ActiveSupport::Concern

    included do
    end

    def latest_jobs
      unless @latest_jobs_cache
        @latest_jobs_cache = jobs.where.not(
          id: Job
              .joins('INNER JOIN jobs AS linked_jobs ON jobs.id = linked_jobs.original_job_id')
              .joins(:job_group) # avoid full table scan on inner query by constraining it to the relevant batch
              .where(job_groups: { batch_id: id })
        )
      end
      @latest_jobs_cache
    end
  end
end

app/models/concerns/batch/batch_validations.rb
class Batch < ActiveRecord::Base
  module BatchValidations
    extend ActiveSupport::Concern

    included do
      validates :name, :version, presence: true
      validates_associated :project
    end
  end
end

app/models/script.rb
class Script < ActiveRecord::Base
  include ScriptValidations

  belongs_to :target
  has_many   :projects
  has_many   :target_fields, class_name: 'Field', through: :target
  has_many   :execution_variables, as: :owner, class_name: 'Field', dependent: :destroy

  validates :target, presence: true

  accepts_nested_attributes_for :execution_variables, reject_if: :all_blank, allow_destroy: true

  delegate :requires_build?, to: :target
end

app/controllers/api/batches_controller.rb
class Api::BatchesController < Api::ApiController
  before_filter :fetch_project, only: [:create]
  include Roar::Rails::ControllerAdditions
  respond_to :json

  def create
    version            = params[:version]
    build              = params[:build]
    tests_per_job      = params[:tests_per_job] || 10
    target_information = params[:target_information]
    # The values for these can be comma separated to make posting from cURL and clients easier
    execution_variables = params[:execution_variables] || {}
    execution_variables['tests_per_job'] = tests_per_job unless execution_variables['tests_per_job'].present?
    batch_params = params[:batch] || {}
    batch_params[:generate_name] = !batch_params[:name].present?

    @batch = BatchCommands::BuildBatchCommand.build(
      batch_params.merge(project_id:          @project.id,
                         version:             version,
                         build:               build,
                         tests_per_job:       tests_per_job,
                         target_information:  target_information,
                         execution_variables: execution_variables)
    )

    if @batch.save
      respond_with @batch, represent_with: BatchRepresenter
    else
      render_model_with_errors(@batch)
    end
  end

  def show
    @batch = Batch.find_by_id(params[:id])
    if @batch.present?
      respond_with @batch, represent_with: BatchJobGroupRepresenter
    else
      render status: :not_found, json: { errors: [t('.not_found')] }
    end
  end

  def index
    page     = params[:page] || 1
    per_page = params[:per_page] || 20
    batches  = Batch.includes(:project).paginate(page: page, per_page: per_page).order('created_at desc').to_a
    respond_with batches, represent_items_with: BatchRepresenter
  end

  def download_build
    @batch = Batch.find_by_id(params[:batch_id])
    build = if params['file_name'].nil?
              @batch.assets.first
            else
              @batch.assets.where(file: params['file_name']).first
            end
    redirect_to build.asset.expiring_url(10 * 60)
  end

  private

  def fetch_project
    @project = Project.find_by_id(params[:project_id])
    unless @project
      render status: :not_found, json: { errors: [t('.project_not_found')] }
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_filter :get_batch, only: %i[show filter_jobs chart_data cancel_jobs]

  def index
    # This callback is very expensive, turn it off when execution_variables aren't important
    Project.skip_callback(:initialize, :after, :set_default_execution_variables)
    @filter_query = BatchQueries::Filters.new(params[:search])
    @page    = params[:page] || 1
    @batches = @filter_query.scope.includes(:project, :test_cases, job_groups: [:test_results]).page(params[:page]).order('created_at desc')
  end

  def filter
    @batches = Batch.includes(:project).where(state: params[:state]).page(params[:page]).order('created_at desc')
    render :index
  end

  def show
    if params[:view] == 'artifacts'
      @artifacts = {}
      @batch.jobs.each do |j|
        j.images.each do |i|
          name = i[0]
          file = i[1]
          @artifacts[name] = {} unless @artifacts[name]
          @artifacts[name][j.job_group.queue_name] = file
        end
      end
      render template: 'batches/artifacts_view', layout: 'scrollspy_menu'

    # Default view
    else
      @jobs = @batch.jobs.order(:job_group_id, :job_name).group_by(&:job_group_id)
      render layout: 'scrollspy_menu'
    end
  end

  def cancel_jobs
    @batch.jobs.queued.each(&:cancel!)
    redirect_to @batch, notice: 'Queued jobs cancelled'
  end

  def new
    @batch = Batch.new(params[:batch].blank? ? {} : batch_params)

    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def create
    if batch_params['project_id'].empty?
      @batch = Batch.new(params[:batch].blank? ? {} : batch_params)
      render action: 'new'
    else
      @batch = BatchCommands::BuildBatchCommand.build(batch_params)
      if @batch.save
        redirect_to @batch, notice: 'Batch was successfully created.'
      else
        # Required as job_groups is a generated required parameter and so shouldn't be displayed
        @batch.errors.messages.reject! { |k, _v| k == :job_groups }
        render action: 'new'
      end
    end
  end

  def filter_jobs
    @jobs = @batch.jobs.where(state: params[:state]).page(params[:page]).order(:created_at).group_by(&:job_group_id)
    render action: 'show', layout: 'scrollspy_menu'
  end

  def chart_data
    @chart_data = @batch.chart_data
  end

  private

  def get_batch
    @batch = Batch.includes(:project).find(params[:id] || params[:batch_id])
  end

  def batch_params
    @batch_params = params.require(:batch).permit! # (:name, :project_id, :version, :build)
    @batch_params[:target_information]  = params[:batch][:target_information]
    @batch_params[:execution_variables] = params[:batch][:execution_variables]
    @batch_params
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
  def additional_variables
    defaults = Builders::Base::SPECIAL_EXECUTION_VARIABLES.keys.map(&:to_s)
    params   = @batch.execution_variables.reject { |a| defaults.include?(a) }
    params.merge(@batch.target_information) if @batch.target_information
    params
  end
end

app/views/batches/_form.html.erb
<%= simple_form_for @batch do |f| %>
  <div class="wizard" data-initialize="wizard" id="batchWizard">
    <div class="steps-container">
      <ul class="steps">
        <li data-step="1" data-name="batchInfo" class="active"><span class="badge">1</span>Batch Information<span class="chevron"></span></li>
      </ul>
    </div>
    <div class="actions">
      <button type="button" class="btn btn-default btn-prev"><span class="glyphicon glyphicon-arrow-left"></span>Prev</button>
      <button type="button" class="btn btn-default btn-next" data-last="Finish">Next<span class="glyphicon glyphicon-arrow-right"></span></button>
      <input type="submit" class="btn btn-default btn-next hidden">
    </div>
    <div class="step-content">
      <div class="step-pane active sample-pane alert" data-step="1">
        <h4>Batch Details</h4>
        <p><%= f.input :name %></p>
        <p><%= f.association :project %></p>
        <p><%= f.input :version %></p>
      </div>
      <div class="step-pane sample-pane-alert" id="build">
        <h4>Build</h4>
        <p>Please attach a build</p>
        <%= render "fields/array", field_name: :build, f: f %>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $.fn.add_queue = function() {
      this.wizard('addSteps', -1, [
        {
          label: 'Queue information',
          pane: $('#queue').html()
        }
      ]);
      $(document).ready(queue_remove_item);
      $(document).on('page:load', queue_remove_item);
      return this;
    };

    $.fn.add_jobs = function() {
      this.wizard('addSteps', -1, [
        {
          label: 'Jobs',
          pane: '<div id="jobs">' + $('#job').html() + '</div>'
        }
      ]);
      return this;
    };

    $.fn.add_tv_target = function() {
      this.wizard('addSteps', -1, [
        {
          label: 'Application details',
          pane: $('#tv_targets').html()
        }
      ])
    };

    $.fn.add_build = function() {
      this.wizard('addSteps', -1, [
        {
          badge: '',
          label: 'Build information'
        }
      ]);

      tabId = $.fn.get_tabs().indexOf('Build information')
      $($('div[data-step~="'+ (Number(tabId)+1) + '"]')[0]).attr('data-step', '')
      $('#build').attr('data-step', (Number(tabId)+1));
      return this;
    };

    $.fn.add_other = function() {
      this.wizard('addSteps', -1, [
        {
          label: 'Execution variables',
          pane: $('#other').html()
        }
      ])
    };

    $.fn.get_tabs = function() {
      var option_all = $("#batchWizard div ul li").map(function(){
        return $.trim($(this).text().substring(1));
      }).get();
      return option_all
    }

    $(document).ready(function(){
      var wizard = $('#batchWizard').wizard();
      wizard.on('finished.fu.wizard', function(e, data){
        $('input[type=submit]').click();
      });

      wizard.on('actionclicked.fu.wizard', function(evt, data){
        if (data['step'] == 1 && data['direction'] == 'next') {
          if ($('#batch_project_id option:selected').index()) {
            form = $('#batchWizard');

            queue_pos = $.fn.get_tabs().indexOf('Queue information');
            if (queue_pos > 0) {
              form.wizard('removeSteps', queue_pos+1, 1);
              form.add_queue();
            }

            jobs_pos = $.fn.get_tabs().indexOf('Jobs');
            if (jobs_pos > 0) {
              form.wizard('removeSteps', jobs_pos+1, 1);
              form.add_jobs()
            }

            $(document).ready(add_array_item);
          }
        }
      });
    });

    if ($('#other').length !== 0) {
      $('#batchWizard').add_other();
    }
  </script>

  <% if @batch.requires_build? %>
    <script type="text/javascript">
      $('#batchWizard').add_build()
    </script>
  <% end %>
  <% unless @batch.script.nil? %>
    <% unless @batch.script.target.fields.empty? %>
      <script type="text/javascript">
        $('#batchWizard').add_tv_target()
      </script>
    <% end %>
  <% end %>
  <% unless @batch.project_id.nil? %>
    <script type="text/javascript">
      form = $('#batchWizard');
      form.add_queue();
      form.add_jobs();
    </script>
  <% end %>
<% end %>

<div class="hidden" >
  <%= simple_form_for @batch  do |f| %>
    <%= f.fields_for :execution_variables, OpenStruct.new(@batch.execution_variables) do |execution_variables_builder| %>
      <% if @batch.execution_variables_required %>
        <%
          queues = @batch.execution_variables_required.select { |a| [:curated_queue, :queues].include? a.name }
          jobs = @batch.execution_variables_required.select { |a| [:tests_per_job, :jobs_per_queue, :tests].include? a.name }
          other = @batch.execution_variables_required - jobs - queues

          # Temporarily remove curated_queues and jobs_per_queue
          queues = queues.select { |a| a.name != :curated_queue }
          jobs = jobs.select { |a| a.name != :jobs_per_queue }
        %>
        <div class="step-pane sample-pane-alert" id="queue">
          <h4>Queue Options</h4>
          <% queues.each do |queue| %>
            <%= render "fields/#{queue.field_type}", field_name: queue.name, f: execution_variables_builder, attribute: @batch.execution_variables %>
          <% end %>
        </div>

        <div class="step-pane sample-pane-alert" id="job">
          <h4>Job Information</h4>
          <% jobs.each do |job| %>
            <%= render "fields/#{job.field_type}", field_name: job.name, f: execution_variables_builder, attribute: @batch.execution_variables %>
          <% end %>
        </div>

        <% unless other.empty? %>
          <div class="step-pane sample-pane-alert" id="other">
            <h4>Execution Variables</h4>
            <% other.each do |other_field| %>
              <%= render "fields/#{other_field.field_type}", field_name: other_field.name, f: execution_variables_builder, attribute: @batch.execution_variables %>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <% unless @batch.script.nil? %>
        <% unless @batch.script.target.fields.empty? %>
          <%= f.fields_for :target_information, OpenStruct.new(@batch.target_information) do |builder| %>
          <div class="step-pane sample-pane-alert" id="tv_targets">
            <h4>Application details</h4>
            <% @batch.script.target.fields.each do |target_field| %>
              <%= render "fields/#{target_field.field_type}", field_name: target_field.name, default: target_field.default_value, f: builder%>
            <% end %>
          </div>
          <% end %>
        <% end %>
      <% end %>



    <% end %>
  <% end %>
</div>

app/views/batches/artifacts_view.html.erb
<head>
  <% provide(:title, "Artifact Details: #{@batch.name}") %>
</head>
<div class="col-md-2 hidden-sm hidden-xs" id="sidenav">
  <ul class="sidebar nav nav-pills nav-stacked nav-stacked-tight">
    <li><a href="#details" class="active">details</a></li>
    <% @artifacts.each do |a, b| %>
        <li><a class="nav-stacked-tight" href="#file_<%= a.sub('.', '-') -%>"><%= a -%></a></li>
    <% end %>
  </ul>
</div>

<div class="col-md-10">

  <div class="row" id="details">

    <h3>Batch details: <%= @batch.name %></h3>
    <%= hidden_field_tag :batch_id, @batch.id %>
    <%= hidden_field_tag :page, @page %>


    <h4>Project: <span class="label label-project"><%= @batch.project.id -%> </span>
      <em><%= link_to @batch.project.name, project_path(@batch.project) %></em></h4>

    <p><strong>Version:</strong> <code class="version-label"><%= @batch.version %></code></p>

    <a href="<%= batch_url(@batch) %>" class="btn btn-small btn-default">Switch to batch view</a>


    <br/>
    <br/>
  </div>

  <div class="row">

    <% row_index = 1 %>

    <% @artifacts.each do |a, q| %>

        <% image_index = 1 %>

        <div class="panel panel-default" id="file_<%= a.sub('.', '-') -%>">

          <div class="panel-heading"><h5 class="panel-title"><%= a -%></h5></div>

          <div class="panel-body">
            <% q.each do |queue, image| %>
                <% image_url = image %>
                <div class="screenshot col-md-4 col-sm-6 col-lg-3 thumbnail">
                  <%= image_tag image_url, class: 'img-responsive', 'data-toggle' => 'modal', 'data-target' => "#image-popup-#{row_index}-#{image_index}" %>
                  <div class="caption">
                    <span class="label label-info"><%= queue -%></span>
                  </div>
                </div>
                <div class='modal fade' id='image-popup-<%= row_index %>-<%= image_index %>' tabindex='-1' role='dialog' aria-labelledby='image-popup-<%= image_index %>-Label'>
                  <div class='modal-dialog' role='document'>
                    <%= image_tag image_url, class: 'img-responsive' %>
                  </div>
                  <div class='modal-footer'>
                    <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
                  </div>
                </div>
                <% if image_index % 4 == 0 %>
                    <div class="clearfix visible-lg-block"></div>
                <% elsif image_index % 3 == 0 %>
                    <div class="clearfix visible-md-block"></div>
                <% elsif image_index % 2 == 0 %>
                    <div class="clearfix visible-sm-block"></div>
                <% end %>

                <% image_index += 1 %>
            <% end %>
            <% row_index += 1 %>
          </div>
        </div>
    <% end %>


  </div>

</div>

app/views/batches/index.html.erb
<head>
  <% provide(:title, "Recent Test Batches") %>
</head>
<h3>Recent Test Batches</h3>

<%= hidden_field_tag :batch_index %>
<%= hidden_field_tag :page, @page %>

<div class="row">
  <div class="col-sm-2">
    <%= link_to( 'Create batch', new_batch_path, :class => 'btn btn-primary') %>
  </div>
  <div class="col-sm-10">
  <%= simple_form_for @filter_query, as: :search, url: batches_path, method: :get, html: { id: "batches_filter", class: 'form-search' } do |f| %>
    <%= f.input_field :project_ids, as: :select, placeholder: "Filter by project", label: false, multiple: true, collection: Project.joins(:batches).uniq %>
  <% end %>
  </div>
</div>
  
<br />

<div class="row">

<table class="table">
  <tr>
    <th>ID</th>
    <th>Batch</th>
    <th>Version</th>
    <th>Status</th>
    <%= render partial: "shared/status_headings" %>
    <th>Submitted</th>
  </tr>
  <%= content_tag_for(:tr, @batches) do |batch| %>
    <td><%= batch.id -%></td>
    <td><%= link_to truncate(batch.name, length: 80), batch_path(batch) %></td>
    <td><code class="version-label"><%= batch.version %></code></td>
    <td>
      <span id=<%= "batch_#{batch.id}_state" %>>
        <%= status_badge(batch.state) %>
      </span>
    </td>
    <%=
        render partial: "shared/status_counts",
               locals: {
                   id:     batch.id,
                   type:   'batch',
                   queued: batch.jobs_queued,
                   running: batch.jobs_running,
                   passed: batch.jobs_passed,
                   failed: batch.jobs_failed,
                   errored: batch.jobs_errored }
    %>
    <td><%= batch.created_at.to_s(:short) %></td>
  <% end %>
</table>

<%= will_paginate @batches %>

</div>

app/views/batches/new.html.erb
<head>
  <% provide(:title, "Create A New Batch") %>
</head>
<div class="page-header">
  <h1><%= t '.title', default: [:'helpers.titles.new', 'Create a new batch'], model: 'Batch' %></h1>
</div>

<% if @batch.errors.any? %>
    <ul>
      <% @batch.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= render :partial => 'form' %>

app/views/batches/new.js.erb
$("#new_batch").html("<%= escape_javascript(render partial: "batches/form") %>");
batch_create();
array_field();

app/views/batches/show.html.erb
<head>
  <% provide(:title, "Batch Details: #{@batch.name}") %>
</head>
<div class="col-md-2 hidden-sm hidden-xs" id="sidenav">
  <ul class="sidebar nav nav-pills nav-stacked">
    <li class="active"><a href="#batch_details">details</a></li>
    <% @jobs.each do |group_id, jobs| %>
        <li><a href="#group_<%= group_id %>"><%= jobs.first.job_group.queue_name %></a></li>
    <% end %>
  </ul>
</div>

<div class="col-md-10">


  <div class="row">
    <div class="col-md-8 col-sm-8">


      <h3 id="batch_details">Batch details: <%= @batch.name %></h3>
      <%= hidden_field_tag :batch_id, @batch.id %>
      <%= hidden_field_tag :page, @page %>


      <h4>Project: <span class="label label-project"><%= @batch.project.id -%> </span>
        <em><%= link_to @batch.project.name, project_path(@batch.project) %></em></h4>

      <p><strong>Version:</strong> <code class="version-label"><%= @batch.version %></code></p>
      <% unless @batch.assets.empty? %>
          <p>
            <strong>Builds:</strong>
            <% @batch.assets.each do |build| %>
                <em><%= build.file %></em>
            <% end %>
          </p>
      <% end %>
      <% additional_variables.each do |key, value| %>
          <p>
            <strong><%= key.humanize %>:</strong>
            <%= value %>
          </p>
      <% end %>
      <p><strong>Scheduled:</strong> <%= @batch.created_at.to_s(:short) %></p>
      <% if @batch.jobs.completed_without_error.count > 0 %>
          <p>
            <strong>Testmine:</strong> <%= link_to("Results view", testmine_url(@batch.jobs.completed_without_error.first)) %>
          </p>
      <% end %>
      <% if @batch.jobs.queued.count > 0 %>
          <p><strong>Cancel queued jobs:</strong> <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                                       "/batches/#{@batch.id}/cancel",
                                       :method => :cancel,
                                       :data => {:confirm => "This will cancel all queued jobs in this batch, are you sure?"} %>
          </p>
      <% end %>

      <a href="<%= batch_url(@batch, view: :artifacts) %>" class="btn btn-small btn-default">Switch to artifact view</a>


    </div>

    <div class="col-md-4 col-sm-4 hidden-xs" id=<%= "batch_chart_#{@batch.id}" %>>
      <%= render partial: 'shared/chart', locals: {chart_data: @batch.chart_data, options: {id: 'chart_graph', width: 300, height: 300}} %>
    </div>

  </div>

  <br/>

  <table class="table table-hover table-striped table-responsive">
    <thead>
    <tr>
      <th>Job</th>
      <th></th>
      <th>Device</th>
      <th>Script</th>
      <th>Duration</th>
      <th>Status</th>
      <%= render partial: "shared/status_headings" %>
    </tr>
    </thead>
    <% @jobs.each do |group_id, jobs| %>
        <% if jobs %>
            <thead id=<%= "group_#{group_id}" -%>>
            <tr>
              <td colspan="7"><span class="label label-info"><%= jobs.first.job_group.queue_name -%></span></td>
            </tr>
            </thead>

            <tbody>

            <%= content_tag_for(:tr, jobs, class: 'active') do |job| %>
                <td>
                  <% if job.original_job %>
                      <%= link_to "<span class='glyphicon glyphicon-chevron-up'></span> ##{job.id}".html_safe, job_path(job) %>
                  <% else %>
                      <%= link_to "##{job.id}", job_path(job) %>
                  <% end %>
                </td>
                <td>
                  <% if job.can_retry? %>
                      <%= link_to('<span class="glyphicon glyphicon-repeat"></span>'.html_safe, job_retry_path(job.id), method: 'put', title: 'Retry this job') %>
                  <% elsif job.retried? %>
                      <span class="glyphicon glyphicon glyphicon-ok-circle"></span>
                  <% end %>
                  <% if job.can_cancel? %>
                      <%= link_to('<span class="glyphicon glyphicon-remove"></span>'.html_safe, job_cancel_path(job.id), method: 'put', title: 'Cancel this job') %>
                  <% end %>
                </td>
                <td>
        <span id=<%= "job_#{job.id}_device_details" %>>
           <%= device_name_db_link(job) %>
        </span>
                </td>
                <td>
                  <%= script_duration(job) -%>
                </td>
                <td>
                  <%= job_duration(job) -%>
                </td>
                <td>
        <span id=<%= "job_#{job.id}_state" %>>
          <%= status_badge(job.status) %>
        </span>
                </td>
                <%=
                    render partial: "shared/status_counts",
                           locals: {
                                   id: job.id,
                                   type: 'job',
                                   queued: job.queued_count,
                                   running: job.running_count,
                                   passed: job.passed_count,
                                   failed: job.failed_count,
                                   errored: job.errored_count}
                %>
            <% end %>
            </tbody>
        <% end %>
    <% end %>
  </table>

</div>