config/routes.rb
Hive::Scheduler::Application.routes.draw do
  get 'artifacts/create'

  root 'batches#index'

  resources :batches, only: %w[index show new create] do
    get :chart_data
    get 'filter/:state', on: :collection, action: :filter, as: :filter
    get ':state', action: :filter_jobs, as: :filter
  end

  resources :jobs, only: %w[show] do
    put :retry
    put :cancel
  end

  resources :projects

  namespace :api, defaults: { format: :json } do
    patch '/queues/:queue_names/jobs/reserve' => 'jobs#reserve', defaults: { format: :json }, constraints: { queue_names: /[^\/]*/ }
    post '/jobs/:job_id/artifacts' => 'artifacts#create', defaults: { format: :json }

    resources :batches, only: %w[create show index] do
      get :download_build
      get '/download_build/:file_name', action: :download_build
    end
    resources :jobs do
      patch :prepare
      patch :start
      patch :end
      patch :update_results
      patch :complete
      patch :error
      put :report_artifacts
    end
    resources :projects do
      get :show
    end
  end

  namespace :admin do
    resources :scripts, except: %w[destroy]
  end

  get '/queues' => 'monitoring#dashboard'
  post '/queues/:hive_queue_id/cancel' => 'monitoring#cancel_jobs'
  get '/workers' => 'monitoring#workers'
  get '/usage' => 'monitoring#usage'
  get '/job_status' => 'monitoring#job_status'
  get '/job_status/project/:project_id' => 'monitoring#job_status_project_graph', as: 'job_status_project'

  # Usage stats as json
  get '/usage/batch_counts' => 'monitoring#batch_counts'
  get '/usage/project_counts' => 'monitoring#project_counts'
  get '/usage/device_hours' => 'monitoring#device_hours'

  post '/batches/:id/cancel' => 'batches#cancel_jobs'

  get '/status' => 'api/status#show'

  # Omniauth callbacks
  post '/auth/:provider/callback' => 'application#auth_callback'
  get '/auth/:provider/callback' => 'application#auth_callback'
end

app/views/layouts/_favicons.html.erb
    <%= favicon_link_tag( 'apple-touch-icon-57x57.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '57x57' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-60x60.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '60x60' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-72x72.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '72x72' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-76x76.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '76x76' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-114x114.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '114x114' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-120x120.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '120x120' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-144x144.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '144x144' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-152x152.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '152x152' ) -%>
    <%= favicon_link_tag( 'apple-touch-icon-180x180.png', rel: "apple-touch-icon", :type => 'image/png', :sizes => '180x180' ) -%>

    <%= favicon_link_tag( 'favicon-32x32.png', rel: "icon", :type => 'image/png', :sizes => '32x32' ) -%>
    <%= favicon_link_tag( 'favicon-194x194.png', rel: "icon", :type => 'image/png', :sizes => '194x194' ) -%>
    <%= favicon_link_tag( 'favicon-96x96.png', rel: "icon", :type => 'image/png', :sizes => '96x96' ) -%>
    <%= favicon_link_tag( 'favicon-192x192.png', rel: "icon", :type => 'image/png', :sizes => '192x192' ) -%>
    <%= favicon_link_tag( 'favicon-16x16.png', rel: "icon", :type => 'image/png', :sizes => '16x16' ) -%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="nav-hive-logo" href="/"> <%= image_tag "hive-20.png", alt: "Hive" %></a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if controller_name == "batches" %>"><%= link_to 'Batches', batches_path %></li>
        <li class="<%= "active" if controller_name == "projects" %>"><%= link_to 'Projects', projects_path %></li>
        <li class="<%= "active" if controller_name == "scripts" %>"><%= link_to 'Scripts', admin_scripts_path %></li>
        <li class="dropdown <%= 'active' if controller_name == 'monitoring' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Monitoring <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/queues">Queues</a></li>
            <li><a href="/workers">Workers</a></li>
            <li><a href="/usage">Usage</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

          <li><%= link_to( current_user.uid, user_link(current_user)) -%></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if Chamber.env.sidebar? %>
              <% Chamber.env.sidebar.each do |row| %>
                  <% if row == 'divider' %>
            <li class="divider"></li>
                  <% else %>
            <li><a href="<%= row['link'] %>"><%= row['label'] %></a></li>
                  <% end %>
              <% end %>
            <li class="divider"></li>
            <% end %>
            <li><a href="http://bbc.github.io/hive-ci/">Learn more</a></li>
            <li><a href="https://github.com/bbc/hive-scheduler/issues">Raise an issue</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? "HIVE - #{yield(:title)}" : "HIVE" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= render partial: 'layouts/favicons' %>

  <%= javascript_include_tag "application" %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//www.fuelcdn.com/fuelux/3.11.0/css/fuelux.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//www.fuelcdn.com/fuelux/3.11.0/js/fuelux.min.js"></script>

</head>
<body class="fuelux">

<%= render partial: "layouts/navigation" %>

<div class="container-fluid">
  <%= bootstrap_flash %>
  <div class="row-fluid">

    <% cache('stats_panel', :expires_in => 2.minutes) do %>
        <div class="col-lg-2 hidden-md hidden-sm hidden-xs">
          <ul class="nav nav-pills nav-stacked">

            <li class="dark"><a>Hive Status</a></li>
            <ul class="nav nav-pills nav-stacked">
              <% if @version.to_s != '' %>
                  <li class="light"><a href="https://github.com/bbc/hive-scheduler/releases/tag/<%= @version -%>">Version:
                    <code class="pull-right"><%= @version -%></code></a></li>
              <% end %>
              <li class="light"><a>Running Jobs:<span class="badge badge-result badge-warning pull-right"><%= "#{@counts['running']}" %></span></a>
              </li>
              <li class="light"><a>Queued Jobs:<span class="badge badge-result badge-info pull-right"><%= "#{@counts['queued']}" %></span></a>
              </li>
            </ul>
            </li>
            <br/>
          </ul>
        </div>
    <% end %>

    <div class="col-lg-10 col-sm-12">
      <%= yield %>
    </div>
  </div>
</div>
</div>

<footer>
  <div class="col-md-12">
    <hr/>
    <p class="text-center">&copy; BBC HIVE <%= Date.today.year %></p>
  </div>
</footer>

</body>
</html>

app/views/layouts/scrollspy_menu.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? "HIVE - #{yield(:title)}" : "HIVE" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= render partial: 'layouts/favicons' %>

  <%= javascript_include_tag "application" %>
</head>
<body data-spy="scroll" data-target="#sidenav">

<%= render partial: "layouts/navigation" %>

<div class="container-fluid">
  <%= bootstrap_flash %>
  <div class="row-fluid">
    <%= yield %>
  </div>


</div>
<!-- /container -->

<footer>
  <div class="col-md-12">
    <hr/>
    <p class="text-center">&copy; BBC HIVE <%= Date.today.year %></p>
  </div>
</footer>

</body>
</html>